import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import {ThemeProvider} from '@mui/material/styles';
import theme from "@/theme/theme";
import {store} from '@/app-state/app-store'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import SessionProviderx from "@/components/provider/SessionProviderx";
import QueryProvider from "@/components/provider/QueryProvider";
import StateProvider from "@/components/provider/StateProvider";
import Chakra from "@/components/provider/Chakra";
import { getServerSession } from "next-auth"
import { redirect } from "next/navigation";
import { authOptions } from "@/app/api/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const state=store.getState()
  const session = await getServerSession(authOptions)
  if(session) redirect("/")
  return (
    <html
      lang='en'
      className={`${inter.className} h-full scroll-smooth antialiased`}
    >
      <body
      style={{
        backgroundImage:"url('/background-sn1.jpg')",
       }}
      className='h-full grid place-items-center'>
    <AppRouterCacheProvider>
      <QueryProvider>
      <SessionProviderx>
    <StateProvider>
    <ThemeProvider theme={theme}>
      <Chakra>
    {children}
    </Chakra>
    </ThemeProvider>
    </StateProvider>
    </SessionProviderx>
    </QueryProvider>
    </AppRouterCacheProvider>
    </body>
    </html>
  )
}

